### ISSUE TITLE
“testEnergyManagementAlgorithm”is not a valid simulink model file: could not open source package.

### ISSUE THREAD

**Issue by roanhope** [DLR-VSDC/IEEE-MVC-2023#1]
There are an error " 'testEnergyManagementAlgorithm.slx' is not a valid simulink model file: could not open source package. " when I open the testEnergyManagementAlgorithm.slx.

**Comment by JBRDLR** [comment]
Can you please proof the MATLAB version? Please check all steps of the installation and initialization: https://github.com/DLR-VSDC/IEEE-MVC-2023/blob/main/Installation.md

**Comment by roanhope** [comment]
> Can you please proof the MATLAB version? Please check all steps of the installation and initialization: https://github.com/DLR-VSDC/IEEE-MVC-2023/blob/main/Installation.md

Thanks for reply!
I have try Matlab Version R2021b and 2022a, both of them show  the same error.
![errors_in_simulink](https://user-images.githubusercontent.com/13587144/204724141-ab29ea07-201f-4c18-bbfc-d2a514d20920.JPG)

**Comment by JBRDLR** [comment]
Please call in the command line of MATLAB the following commands and post the results here:
`version`
`computer`
Have you followed all steps of the installation procedure and used a GIT tool on your PC?
In the appendix i added the Alpha version as a release zip, you may also try this.
Everything could be tested on Windows machines successfully. 
[IEEE-MVC-2023_Dev-Alphaversion.zip](https://github.com/DLR-VSDC/IEEE-MVC-2023/files/10120601/IEEE-MVC-2023_Dev-Alphaversion.zip)

**Comment by roanhope** [comment]
> Please call in the command line of MATLAB the following commands and post the results here: `version` `computer` Have you followed all steps of the installation procedure and used a GIT tool on your PC? In the appendix i added the Alpha version as a release zip, you may also try this. Everything could be tested on Windows machines successfully. [IEEE-MVC-2023_Dev-Alphaversion.zip](https://github.com/DLR-VSDC/IEEE-MVC-2023/files/10120601/IEEE-MVC-2023_Dev-Alphaversion.zip)

I used to download the zip file, after i use a GIT tool, it works.
Thanks for your help!
