### ISSUE TITLE
Discrepances in electric motor losses

### ISSUE THREAD

**Issue by tobolar** [DLR-VSDC/IEEE-MVC-2023#16]
From https://github.com/DLR-VSDC/IEEE-MVC-2023/issues/14#issuecomment-1377822635:

Hi, after some simulations and tries, I noticied that the power losses measured from electricMotorBusFM.Ploss is not equal to the calculated by eq:
```
Ploss = Pinv + Pcu + Piron + Pfric
Pcu = 1.5 Iq^2rs;
Piron = 0.095*(wm) + 0.00009*(wm)^2;
Pinv = 95 + 5Iq;
Pfric = 0.155 wm;
```

being:
```
Iq = electricMotorBusFM.I_q
wm = electricMotorBusFM.angVel
```
for a given instant of time.

I have a smaller value with the equation. Do you know where could be the problem or what am I missing?

Thanks!

**Comment by JBRDLR** [comment]
Dear @agubucciarelli please refer to our general answer to this topic:
https://github.com/DLR-VSDC/IEEE-MVC-2023/discussions/17

Best

Jonathan
