### ISSUE TITLE
Access violation

### ISSUE THREAD

**Issue by grisamgit** [DLR-VSDC/IEEE-MVC-2023#20]
We are experiencing the same issue.

![image](https://user-images.githubusercontent.com/67792862/216013052-a7fccef9-4879-48e8-b06a-9fa7ae4b4f14.png)

It is a fresh Matlab installation: 9.13.0.2126072 (R2022b) Update 3.

The PC is an Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz   3.50 GHz, 64-bit operating system, x64-based processor.
Windows specification:
Edition	Windows 10 Pro
Version	21H2
OS build	19044.2486
Experience	Windows Feature Experience Pack 120.2212.4190.0

We tried on two different PCs, and the same error occurs.

_Originally posted by @grisamgit in https://github.com/DLR-VSDC/IEEE-MVC-2023/discussions/7#discussioncomment-4839017_

**Comment by grisamgit** [comment]
Hi everyone.
It seems the root cause of this error lies in the new version of the Simulink file.

**Comment by grisamgit** [comment]
Hi everyone,
I believe I fixed it.
When downloading the folder be sure to download separately also all the .dll files in folder MVC2023_SIM_FMU/binaries/ and all .fmu files in IEEE-MVC-2023/MVCExportedFMUs/.
By the way, even when linking through git, the files get not downloaded.
Samuele

**Comment by JBRDLR** [comment]
@grisamgit:

have you validated that you followed of all this points: https://github.com/DLR-VSDC/IEEE-MVC-2023/discussions/19#discussioncomment-4849751 ?
We tested it yesterday on a different PC and had no trouble, all files were synced.
Best Jonathan
