### ISSUE TITLE
Lateral acceleration issue

### ISSUE THREAD

**Issue by agubucciarelli** [DLR-VSDC/IEEE-MVC-2023#27]
Hi! I noticed that the model has a saturation on the maximum lateral acceleration and equals to "ay_max"=3. But if I plot V^2/R against the output of the model "ay", it is clearly seen that "ay" is limited and V^2/R is sometimes bigger than 3. Why is that constraint there? In order to follow the reference curvature, "ay" should be equal V^2/R, right?
Image reference: Yellow (ay model output)       Blue (calculated V^2/R)
![bug](https://user-images.githubusercontent.com/121059262/216982940-f9a9cd2e-3e11-4625-85f3-da1fed10562d.png)

**Comment by imeb** [comment]
Dear @JBRDLR,
I have increased it to **10m/s2** and the vehicle is stable and the comparison in lateral acceleration is (for track8 OptMunich1):
<img width="727" alt="test" src="https://user-images.githubusercontent.com/77015600/217980509-669c81bf-fe6f-44b7-b3de-7553c3c70013.png">
Best,
Iman

**Comment by JBRDLR** [comment]
Fixed with final release
