### ISSUE TITLE
Extend state vector in the EMA 

### ISSUE THREAD

**Issue by rpintodecastro** [DLR-VSDC/IEEE-MVC-2023#8]
One of the competitors would like to access more vehicle states, including
- lateral acceleration
- torque/force requested by the velocity controller.

This is a reasonable request. We can also add longitudinal acceleration.

**Comment by Fantasydog05** [comment]
Thank you so much. I would like to ask other vehicle states. Could the angular velocity of the motors and yaw rate be available? Angular velocity of a motor could be provided by MCU. Yaw rate could be provided by IMU.
 The mentioned variables in the program are attached in the figure below.
![image](https://user-images.githubusercontent.com/87512543/209902696-2afc9a6d-6be1-4116-bf12-858ce0ca04c4.png)

**Comment by JBRDLR** [comment]
Dear @Fantasydog05 i recognized that @imeb already integrated them all in the vehicle bus. You can to select the desired signals by your self:
![image](https://user-images.githubusercontent.com/110536277/210208257-067dd8dd-c1f3-4511-8d6d-49673b77167d.png)

**Comment by agubucciarelli** [comment]
Hello! Is there a variable available that refers to the "reference current" that should be supplied by the battery and the FC? I only found on the vehiclebus the real current of the battery and the real power of the FC. Having the reference current would be helpful and is a common variable available for EMA design.

**Comment by JBRDLR** [comment]
What do you expect to be the reference current?
If you searching for the current set point for the electric machine I_q might be the right quantity:
![image](https://user-images.githubusercontent.com/110536277/211569805-b3df06f5-efd7-491c-a76c-cfcd93704fd1.png)

Best Jonathan

**Comment by agubucciarelli** [comment]
By reference current I mean the total current that should be supplied by the power source in order to obtain the reference torque that the velocity controller calculates. Yes, I think that the current set point for the electric machine is ok! Thanks!
