### ISSUE TITLE
Wrong signal names from vehicle model

### ISSUE THREAD

**Issue by scoleli** [DLR-VSDC/IEEE-MVC-2023#9]
Hello,
we have just noticed that some motors' output signals from the Modelica vehicle model may have an improper name. In particular, the power balance for each motor seems not correct: apart for the sign, the losses (Ploss) are sometimes greater than the absorbed electrical power (ePower); then, the mechanical output power (mechPower) is too small when compared with the input electrical power, resulting in an impractical efficiency.

We think that the names of these signals are somehow reversed.

Moreover, we would like to point out that the signs of some quantities seems strange according to the common convention. For example, the current (Iq) is negative when the machine is motoring, as well as the electrical power and the mechanical power. Can you explain us the convention you adopted in your model, please?

Kindly,

Elia

**Comment by JBRDLR** [comment]
Hi Elia, 

it always depends how the flow sensor is connected in Modelica, that might result in different signs.

Please explain your concern regarding the losses in more detail (full signalnames, plots, …) otherwise it is hard to give a solution answer.

best,

Jonathan

**Comment by JBRDLR** [comment]
@scoleli i did a simulation of the FTP75 and created a plot of the first 400s. To me these appear correct.
Please find also the figure in the appendix, with these you can further discuss this issue.
[Link to figures](https://gigamove.rwth-aachen.de/de/download/6a2bb67200ee88502a329e380deeb72f)

![image](https://user-images.githubusercontent.com/110536277/210216184-55357a31-974c-465b-b4de-eb17b8e624e7.png)

**Comment by scoleli** [comment]
Hi Jonathan,
sorry for our dubt, we had a quick look at some initial values last time without doing a complete plot. Now, we have just tried with FPT75 and other cycles and the power balance is always correct as you showed before, except for the sign convention.
Thank you for your reply,

Elia
